#!/bin/sh

DEVICE_SWITCH=$1
DEVICE=$2

# ===================================================================
# nix/home-manager - https://github.com/nix-community/home-manager
# ===================================================================

install_home_manager()
{
  HOME_MANAGER_VERSION=$(home-manager --version)
  if [ $? -eq 0 ]; then
    echo "home-manager is already installed version=[$HOME_MANAGER_VERSION]"
  else
    HOME_MANAGER_ARCHIVE_URL=https://github.com/nix-community/home-manager/archive/master.tar.gz
    echo "installing home-manager from $HOME_MANAGER_ARCHIVE_URL"

    nix-channel --add $HOME_MANAGER_ARCHIVE_URL home-manager
    nix-channel --update
    nix-shell '<home-manager>' -A install
  fi
}

check_device()
{
  # check that a supported device is given as an argument
  SUPPORTED_DEVICE_KAWASAKI="kawasaki"
  SUPPORTED_DEVICE_MECHANICAL_ORCHARD_M2_MACBOOK="mechanical-orchard-m2-macbook"
  SUPPORTED_DEVICES="$SUPPORTED_DEVICE_KAWASAKI $SUPPORTED_DEVICE_MECHANICAL_ORCHARD_M2_MACBOOK"
  echo "supported devices=$SUPPORTED_DEVICES"

  if [ $DEVICE_SWITCH != "--device" ] || [ -z $DEVICE ]; then
    echo "--device <device_name> is required"
    exit 1
  fi

  if [ $DEVICE = $SUPPORTED_DEVICE_KAWASAKI ] || [ $DEVICE = $SUPPORTED_DEVICE_MECHANICAL_ORCHARD_M2_MACBOOK ]; then
    echo "supported device=$DEVICE"
  else
    echo "unsupported device=$DEVICE"
    exit 1
  fi
}

switch_home()
{
  # download the latest rupurt/nix-home if we don't have it
  if [ ! -e 'install_home_manager' ]; then
    NIX_HOME_ARCHIVE_URL=https://github.com/rupurt/nix-home/archive/refs/heads/main.zip
    echo "fetching nix-home from $NIX_HOME_ARCHIVE_URL"

    curl -sSf -L $NIX_HOME_ARCHIVE_URL -o /tmp/nix-home.zip
    unzip -o /tmp/nix-home.zip -d /tmp
    cd /tmp/nix-home-main
  fi

  # build and switch to the flake of the given device
  cd devices/${DEVICE}
  home-manager switch --flake .
}

# ensure nix is installed and activated in the current shell
if [ -x "$(command -v nix --version)" ]; then
  install_home_manager
  check_device
  switch_home
else
  echo "nix is not installed or activated in the current shell"
fi
