#!/bin/sh

# ===================================================================
# nix - https://nixos.org/download.html
# ===================================================================

install_nix()
{
  # 2.15.0 breaks home-manager with new profile location
  # - https://github.com/NixOS/nix/issues/7930
  curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
  source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
}

# install nix if it's not currently installed and activated
NIX_VERSION=$(nix --version)
if [ $? -eq 0 ]; then
  echo "nix is already installed version=[$NIX_VERSION]"
else
  install_nix
fi
